### ISSUE TITLE
RGBA_8888 rather than BGRA_8888

### ISSUE THREAD

**Issue by carrotalan** [lineage-rpi/android_frameworks_native#1]
Hi There,

I have a series of 3rd party applications that depend on ImageReader being set to RBGA_8888 (0x1) rather than BGRA_8888 (0x5). TeamViewer Host is the main problem:

`10-01 13:08:48.644  1986  2960 E AndroidRuntime: java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.`

I have never compiled Android drivers before and don't know enough about low level graphics :(. I can sort of see what may need to change in https://github.com/lineage-rpi/android_frameworks_native/blob/21f013910fd6b7cde6b78fb6d4ac619880ef0e1a/opengl/libs/EGL/eglApi.cpp.

But basically my question is, what is the easiest way to change the system to run in RGBA_8888 and not BGRA. Is this even possible or does it require changing the hardware (Raspberry Pi 3).

**Comment by KonstaT** [comment]
You'd better ask this from peyo-hd. He's done all the display work and according to this (https://github.com/android-rpi/device_brcm_rpi3/wiki#use-hal_pixel_format_bgra_8888) only BGRA_8888 is supported. I don't know if this going to change if we can migrate to newer version of MESA stack later on.
